CREATE TABLE IF NOT EXISTS urls (
  token TEXT PRIMARY KEY,
  url TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS timestamps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT NOT NULL,
  ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (token) REFERENCES urls(token)
);
